const myHero=["shaktiman","naagraj","doga"]
const hero=["prabhash","ajay","salman"]

myHero.push(hero)
console.log(myHero); // ["shaktiman","naagraj","doga",Array(3)] ...
console.log(myHero[3][1]); // ajay ...

myHero.concat(hero)
console.log(myHero); // ["shaktiman","naagraj","doga"] ...

const allHero=myHero.concat(hero)
console.log(allHero); // ["shaktiman","naagraj","doga","prabhash","ajay","salman"] ...

const allHero2=[...myHero,...hero]
console.log(allHero2); // ["shaktiman","naagraj","doga","prabhash","ajay","salman"] ...

const anotherArr=[1,2,3,4,[5,6,7],8,[9,[10,11]]]

const flattedArr=anotherArr.flat(Infinity)
console.log(flattedArr); // [1,2,3,4,5,6,7,8,9,10,11] ...

console.log(Array.isArray("dharamy")) // false ...
console.log(Array.from(["dharm"])) // ["dharm"] ...
console.log(Array.from({name:"dharmy"})) // [] ...

let score1=100
let score2=200
let score3=300

console.log(Array.of(score1,score2,score3)); // [100,200,300] ...